/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Harsh
 */
public class First extends javax.swing.JFrame {

    /**
     * Creates new form First
     */
    String signinCardno;
    String signinPin;
    int balance;
    String signinName;
    String signinEmail;
    public First() {
        initComponents();
    }
    public First(String signinName, String signinEmail, String signinCardno, String signinPin, int balance) {

        this.signinCardno = signinCardno;
        this.signinPin = signinPin;
        this.balance = balance;
        this.signinName = signinName;
        this.signinEmail = signinEmail;
        System.out.println(this.signinName + this.signinEmail);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btndeposit = new javax.swing.JButton();
        btnwithdrawal = new javax.swing.JButton();
        btnfastcash = new javax.swing.JButton();
        btnpinchange = new javax.swing.JButton();
        btnbalanceenquiry = new javax.swing.JButton();
        btnministatement = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Footer10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("PLEASE SELECT YOUR TRANSACTION");

        btndeposit.setBackground(new java.awt.Color(0, 0, 0));
        btndeposit.setForeground(new java.awt.Color(255, 255, 255));
        btndeposit.setText("DEPOSIT");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        btnwithdrawal.setBackground(new java.awt.Color(0, 0, 0));
        btnwithdrawal.setForeground(new java.awt.Color(255, 255, 255));
        btnwithdrawal.setText("WITHDRAWAL");
        btnwithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwithdrawalActionPerformed(evt);
            }
        });

        btnfastcash.setBackground(new java.awt.Color(0, 0, 0));
        btnfastcash.setForeground(new java.awt.Color(255, 255, 255));
        btnfastcash.setText("FAST CASH");
        btnfastcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfastcashActionPerformed(evt);
            }
        });

        btnpinchange.setBackground(new java.awt.Color(0, 0, 0));
        btnpinchange.setForeground(new java.awt.Color(255, 255, 255));
        btnpinchange.setText("PIN CHANGE");
        btnpinchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpinchangeActionPerformed(evt);
            }
        });

        btnbalanceenquiry.setBackground(new java.awt.Color(0, 0, 0));
        btnbalanceenquiry.setForeground(new java.awt.Color(255, 255, 255));
        btnbalanceenquiry.setText("BALANCE ENQUIRY");
        btnbalanceenquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbalanceenquiryActionPerformed(evt);
            }
        });

        btnministatement.setBackground(new java.awt.Color(0, 0, 0));
        btnministatement.setForeground(new java.awt.Color(255, 255, 255));
        btnministatement.setText("MINI STATEMENT");
        btnministatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnministatementActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("EXIT");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        Header.setBackground(new java.awt.Color(0, 255, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        jLabel2.setText("CAPITAL BANK ATM");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Footer10.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout Footer10Layout = new javax.swing.GroupLayout(Footer10);
        Footer10.setLayout(Footer10Layout);
        Footer10Layout.setHorizontalGroup(
            Footer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Footer10Layout.setVerticalGroup(
            Footer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Footer10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btndeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpinchange, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addComponent(btnfastcash, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnbalanceenquiry, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(btnwithdrawal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnministatement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnministatement, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfastcash, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbalanceenquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpinchange, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Footer10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
        Deposit deposit = new Deposit(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        deposit.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btndepositActionPerformed

    private void btnwithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwithdrawalActionPerformed
        Withdrawal withdraw = new Withdrawal(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        withdraw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnwithdrawalActionPerformed

    private void btnfastcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfastcashActionPerformed
        FastCash fastCash = new FastCash(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        fastCash.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnfastcashActionPerformed

    private void btnpinchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpinchangeActionPerformed
        PinChange pinChange = new PinChange(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        pinChange.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnpinchangeActionPerformed

    private void btnbalanceenquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbalanceenquiryActionPerformed
        BalanceEnquiry balanceEnquiry = new BalanceEnquiry(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        balanceEnquiry.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnbalanceenquiryActionPerformed

    private void btnministatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnministatementActionPerformed
        MiniStatement miniStatement = new MiniStatement(this.signinName,this.signinEmail,this.signinCardno,this.signinPin,this.balance);
        miniStatement.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnministatementActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        Signin signin = new Signin(this.signinName,this.signinEmail,this.signinCardno,this.signinPin,this.balance);
        signin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer10;
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnbalanceenquiry;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndeposit;
    private javax.swing.JButton btnfastcash;
    private javax.swing.JButton btnministatement;
    private javax.swing.JButton btnpinchange;
    private javax.swing.JButton btnwithdrawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
